apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: python-app
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app-container
          image: gcr.io/abdelaziz-gke/python-app
          ports:
            - containerPort: 8000
        - name: redis-container
          image: redis
          ports:
            - containerPort: 6379
  selector:
    matchLabels:
      app: python-app